name: conjur-demo
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: curl https://ipinfo.io/ip
        
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.2
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: ${{ secrets.CONJUR_ACCOUNT }}
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: ${{ secrets.CONJUR_SECRETS }}
          certificate: ${{ secrets.CONJUR_PUBLIC_KEY }}
      - name : Echo Secret1
        run: echo $SECRET1 | sed 's/./& /g'