name: github-demo-host
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: infamousjoeg/conjur-action@v2.0.3
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: ${{ secrets.CONJUR_ACCOUNT }}
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: ${{ secrets.CONJUR_SECRETS }}
          certificate: ${{ secrets.CONJUR_PUBLIC_KEY }}
      - name : Echo Secret1
        run: echo $SECRET1 | sed 's/./& /g'
      - name : Echo Secret2
        run: echo $SECRET2 | sed 's/./& /g'