name: github-demo-host
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Authenticate via Authn-JWT"
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          JWT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          echo $JWT_TOKEN | base64
          SESSION_TOKEN=$(curl -k -s --request POST "${{ secrets.CONJUR_URL }}/authn-jwt/${{ secrets.CONJUR_AUTHN_ID }}/${{ secrets.CONJUR_ACCOUNT }}/authenticate" --header "Content-Type: application/x-www-form-urlencoded" --header "Accept-Encoding: base64" --data-urlencode "jwt=$JWT_TOKEN")
          echo $SESSION_TOKEN
          CONJUR_SECRET=$(curl -k -s -H "Authorization: Token token=\"$token\"" "${{ secrets.CONJUR_URL }}/secrets/${{ secrets.CONJUR_ACCOUNT }}/variable/${{ secrets.SECRET_ID }}")
          echo " "
          echo "---- Retrieving Secret Value -----------"
          echo "ID: ${{ secrets.SECRET_ID }}"
          echo "Value: $CONJUR_SECRET"
          echo "----------------------------------------"
          echo " "