name: Test get secrets from conjur-authn-jwt with DEBUG
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Authenticate via Authn-JWT"
          JWT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          echo $JWT_TOKEN
  
          # Authenticate against conjur, get a temporary token
          token=$(curl -k -s --header "Accept-Encoding: base64" --data "$conjur_pass" "$conjur_url"/authn/"$conjur_account"/"$conjur_host"/authenticate)
          # Connect to the Conjur/Conjur REST API to retrieve secret value"
          secret_value=$(curl -k -s --header "Authorization: Token token=\"$token\"" "$conjur_url/secrets/$conjur_account/variable/$secret_id")
          echo " "
          echo "---- Retrieving Secret Value -----------"
          echo "ID: $secret_id"
          echo "Value: $secret_value"
          echo "----------------------------------------"
          echo " "